version: '3'

services:
    bot:
        image: ghcr.io/ertuil/chatgpt-telegram-bot:latest
        command: python main.py
        restart: always
        volumes:
          - ./data:/app/data
        environment:
          - OPENAI_API_KEY=
          - TELEGRAM_BOT_TOKEN=
          - TELEGRAM_ADMIN_ID=
          - DEFAULT_MODEL=gpt-3.5-turbo
          - GOOGLE_API_KEY=
          - GOOGLE_CSE_ID=
